### ISSUE TITLE
Hot reloading for server

### ISSUE THREAD

**Issue by edwmurph** [AdamSiekierski/gatsby-plugin-nodejs#2]
Can the server have hot reloading when starting everything via `gatsby develop`?

I need hot reloading for both the frontend gatsby code changes + the backend express server changes and it seems like this plugin doesn't have a good way to enable that unless I'm missing something?

**Comment by AdamSiekierski** [comment]
Yup, currently you can't do that. I could possibly integrate it with something like nodemon, so that it would watch the filesystem, and automatically restart the server.

Thanks for the suggestion, I will make the improvment in the next version :D

**Comment by edwmurph** [comment]
A nodemon integration would be great!

**Comment by AdamSiekierski** [comment]
Ok, done :D. Had time this afternoon, and created a simple integration with `nodemon` - it has an API that allows me to use it directly inside my code. Check it out, in the version `0.7.0` :). No setup required, it just works :)

**Comment by edwmurph** [comment]
works great! i had to pull it in from this repo directly to test it because it seems like the updated npm package hasn't been published yet? either way thank you!

**Comment by AdamSiekierski** [comment]
Now it's published. I forgot to publish it manually, because in my other repos I have CI set up :). Thanks!
