### ISSUE TITLE
[nodemon] app crashed

### ISSUE THREAD

**Issue by guanacone** [AdamSiekierski/gatsby-plugin-nodejs#3]
When running `gatsby develop` I'm getting:
```
success run page queries - 0.029s - 2/2 69.82/s
[nodemon] app crashed - waiting for file changes before starting...
⠀
You can now view fullstack_app in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 2.814s
```
App is working otherwise. Getting the same message when making changes to the server and have to manually restart it. Any thoughts? Thanks!

**Comment by AdamSiekierski** [comment]
What version of Gatsby are you using, and what operating system do you have?

**Comment by guanacone** [comment]
Thanks for getting back to me and sorry if this is not of your concerns.

OS: Ubuntu 18.04.5 LTS
"gatsby": "2.24.52"

**Comment by AdamSiekierski** [comment]
Well, I've quickly bootstrapped a new project and I can't see that error. It looks like it comes from an another library or something... Be sure to place the server in the `server/index.js` :)

**Comment by guanacone** [comment]
ok, thanks anyway!
